Write deserialisation tests for the api
timeforcoffee/timeforcoffee-android pull request #57
Opened 2018-03-09 16:17 UTC by lucasardonini

2018-03-12 16:30 UTC, FriedrichIII commented on mobile/src/main/java/ch/liip/timeforcoffee/TimeForCoffeeModule.java
> +        Gson gson = new GsonBuilder().create();
@lucasardonini Are you sure about removing the dateFormat? Did you test it?

2018-03-12 16:35 UTC, FriedrichIII requested changes
Reviewed. See my comments.

2018-03-12 16:42 UTC, FriedrichIII commented on mobile/src/main/java/ch/liip/timeforcoffee/TimeForCoffeeModule.java
> +        Gson gson = new GsonBuilder().create();
Tested and it actually breaks the timer countdown. Please fix.

2018-03-16 09:04 UTC, lucasardonini commented
@FriedrichIII Applied your comment.

2018-03-16 12:29 UTC, lucasardonini commented
@FriedrichIII Done changes

2018-03-16 13:12 UTC, FriedrichIII approved these changes

2018-03-16 13:15 UTC, merged