WIP: Handle drawing of the transport way on the map
timeforcoffee/timeforcoffee-android pull request #61
Opened 2018-03-12 13:24 UTC by lucasardonini

2018-03-15 10:37 UTC, FriedrichIII requested changes
Good starting implementation. Let's discuss IRL how to further improve it.

2018-03-15 10:37 UTC, FriedrichIII commented on mobile/src/main/java/ch/liip/timeforcoffee/activity/ConnectionsActivity.java
> +        mStationMapFragment.setup(connections, getResources().getString(R.string.connection_from));
Resources are available in the fragment. Do you really need to pass them as parameter?

2018-03-15 10:37 UTC, FriedrichIII commented on mobile/src/main/java/ch/liip/timeforcoffee/fragment/StationMapFragment.java
>      private void drawTransportPath() {
Maybe we could improve that by using Google direction. For now it displays straight line between checkpoint, which doesn't really match the path used by the transport line.

2018-03-15 10:37 UTC, FriedrichIII commented on mobile/src/main/java/ch/liip/timeforcoffee/fragment/StationMapFragment.java
> +    private static Callbacks sDummyCallbacks = new Callbacks() {
Smells like a workaround for some issue. Could you comment what it fixes and if it is really needed?

2018-03-16 10:32 UTC, lucasardonini commented
@FriedrichIII Comments applied

2018-03-16 13:08 UTC, FriedrichIII approved these changes

2018-03-16 13:09 UTC, FriedrichIII commented on mobile/src/main/java/ch/liip/timeforcoffee/fragment/StationMapFragment.java
>      private void drawTransportPath() {
Created issue #65 to track this

2018-03-16 13:09 UTC, merged